// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go
//
// Generated by this command:
//
//	mockgen -source=publisher.go -destination=publisher_mock.go -package=pubsub
//

// Package pubsub is a generated GoMock package.
package pubsub

import (
	context "context"
	reflect "reflect"

	v1 "github.com/KasumiMercury/primind-remind-time-mgmt/internal/gen/throttle/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPublisher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPublisher)(nil).Close))
}

// PublishRemindCancelled mocks base method.
func (m *MockPublisher) PublishRemindCancelled(ctx context.Context, req *v1.CancelRemindRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRemindCancelled", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRemindCancelled indicates an expected call of PublishRemindCancelled.
func (mr *MockPublisherMockRecorder) PublishRemindCancelled(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRemindCancelled", reflect.TypeOf((*MockPublisher)(nil).PublishRemindCancelled), ctx, req)
}
