version: "2"

linters:
    enable:
        - wsl_v5
        - bodyclose
        - contextcheck
        - fatcontext
        - containedctx
        - exhaustruct
        - exhaustive
        - gosec
        - nilnil
        - nilerr
        - nlreturn
    settings:
        errcheck:
            check-type-assertions: true
            check-blank: true
            disable-default-exclusions: true
            exclude-functions:
                - fmt.Print
                - fmt.Printf
                - fmt.Println
        exhaustruct:
            exclude:
                - 'log/slog\.HandlerOptions'
                - 'net/http\.Server'
                - 'gorm\.io/gorm\.Config'
                - '.*\.RemindModel'
                - 'google\.golang\.org/protobuf/encoding/protojson\.MarshalOptions'
                - 'google\.golang\.org/protobuf/encoding/protojson\.UnmarshalOptions'
                - 'github\.com/ThreeDotsLabs/watermill-nats/v2/pkg/nats\.PublisherConfig'
                - 'github\.com/ThreeDotsLabs/watermill-nats/v2/pkg/nats\.JetStreamConfig'
                - 'github\.com/nats-io/nats\.go/jetstream\.StreamConfig'
        wsl_v5:
            allow-first-in-block: true
            allow-whole-block: false
            branch-max-lines: 2
    exclusions:
        rules:
            - path: _test\.go
              linters:
                  - errcheck
                  - exhaustruct
                  - gosec
                  - staticcheck
                  - fatcontext
                  - containedctx
